# Generated by Django 3.2.23 on 2023-11-21 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='fechaPedido',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 7, 38, 34, 159048, tzinfo=utc)),
        ),
    ]
